server:
  port: 8080
  context-path: /ns1
spring:
  datasource:
    initialize: true
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orca?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: 123456
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  messages:
    basename: i18n/messages        
  thymeleaf:
    cache: false
logging:
  file: /var/log/orca/orca.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    com.morisawa.orca.common.logging: INFO